### ISSUE TITLE
Failed to compile with Python 3.11

### ISSUE THREAD

**Issue by iw17** [pygsl/pygsl#64]
OS: Debian 12
Python: 3.11.2
GCC: 12.2
GSL: 2.7

I tried to install latest `pygsl` (2.3.3) via
```bash
pip install pygsl
```
but it frustratingly failed, and something seemed wrong with the C code. Here is some error info.
```cpp
swig_src/gslwrap_wrap.c: In function ‘_wrap_gsl_blas_zgerc’:
Include/pygsl/complex_helpers.h:54:12: error: request for member ‘dat’ in something not a structure or union
   54 |      ((tmp)->dat[0] = ((PyComplexObject *)(object))->cval.real,\
      |            ^~
swig_src/gslwrap_wrap.c:31044:8: note: in expansion of macro ‘PyGSL_PyCOMPLEX_TO_gsl_complex’
31044 |     if(PyGSL_PyCOMPLEX_TO_gsl_complex(obj0, &tmp) != GSL_SUCCESS)
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Include/pygsl/complex_helpers.h:55:12: error: request for member ‘dat’ in something not a structure or union
   55 |       (tmp)->dat[1] = ((PyComplexObject *)(object))->cval.imag,\
      |            ^~
swig_src/gslwrap_wrap.c: In function ‘_wrap_gsl_blas_cgemm’:
Include/pygsl/complex_helpers.h:61:12: error: request for member ‘dat’ in something not a structure or union
   61 |      ((tmp)->dat[0] = ((PyComplexObject *)(object))->cval.real,\
      |            ^~
swig_src/gslwrap_wrap.c:32871:8: note: in expansion of macro ‘PyGSL_PyCOMPLEX_TO_gsl_complex_float’
32871 |     if(PyGSL_PyCOMPLEX_TO_gsl_complex_float(obj2, &tmp) != GSL_SUCCESS)
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Include/pygsl/complex_helpers.h:62:12: error: request for member ‘dat’ in something not a structure or union
   62 |       (tmp)->dat[1] = ((PyComplexObject *)(object))->cval.imag,\
      |            ^~
Include/pygsl/complex_helpers.h:61:12: error: request for member ‘dat’ in something not a structure or union
   61 |      ((tmp)->dat[0] = ((PyComplexObject *)(object))->cval.real,\
      |            ^~
swig_src/gslwrap_wrap.c:32893:8: note: in expansion of macro ‘PyGSL_PyCOMPLEX_TO_gsl_complex_float’
32893 |     if(PyGSL_PyCOMPLEX_TO_gsl_complex_float(obj5, &tmp) != GSL_SUCCESS)
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Include/pygsl/complex_helpers.h:62:12: error: request for member ‘dat’ in something not a structure or union
   62 |       (tmp)->dat[1] = ((PyComplexObject *)(object))->cval.imag,\
      |            ^~
```
And the rest is too long to paste.

**Comment by PierreSchnizer** [comment]
Please can you check if you are using numpy 2?

Next release will fix it (currently under preparation)

**Comment by iw17** [comment]
> Please can you check if you are using numpy 2?
> 
> Next release will fix it (currently under preparation)

Yes, I was using numpy 2.2, but it made no difference after I downgraded it to 1.26.4.

**Comment by PierreSchnizer** [comment]
There is now a new release 2.5.0
Passed tests on github ci.
Could you check please?

**Comment by iw17** [comment]
> There is now a new release 2.5.0 Passed tests on github ci. Could you check please?

The latest 2.5.0 worked for me! Thanks a lot!
