### ISSUE TITLE
Build failing with swig 4.3.0

### ISSUE THREAD

**Issue by opoplawski** [pygsl/pygsl#67]
With the update to swig 4.3.0 in Fedora rawhide, pygsl fails to compile with lots of the following errors:
```
swig_src/gslwrap_wrap.c: In function ‘_wrap_pygsl_linalg_LU_decomp’:
swig_src/gslwrap_wrap.c:25571:17: error: too few arguments to function ‘SWIG_Python_AppendOutput’; expected 3, have 2
25571 |     resultobj = SWIG_Python_AppendOutput(resultobj,  PyGSL_array_return(_PyMatrix1));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
swig_src/gslwrap_wrap.c:1259:1: note: declared here
 1259 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by PierreSchnizer** [comment]
Being addressed in https://github.com/pygsl/pygsl/pull/68

**Comment by PierreSchnizer** [comment]
being addressed in https://github.com/pygsl/pygsl/pull/66 

I combined it with the upgrade to the meson build system. Let's see if I get both forward at once.

Current status: 
should compile with swig-4.3; but swig-4.3 does not drop None where swig <4.3 was doing it. I have to further investigate it

**Comment by PierreSchnizer** [comment]
Now merged to main.
I need to test it with  gsl-2.8. 
Then I will make a new release.
